### ISSUE TITLE
How to use WorkflowChainUpdater?

### ISSUE THREAD

**Issue by hvelarde** [4teamwork/ftw.upgrade#110]
we are using release 1.19.0 of this package to migrate the workflow of a custom content type; in our upgrade step we must update existing objects, change the workflow used and remove the old one:

the code looks like this (I know this looks a little bit different from the one in the documentation, but I want to know if we can use it in this way):

```python
# -*- coding:utf-8 -*-
from collective.liveblog.interfaces import ILiveblog
from collective.liveblog.logger import logger
from ftw.upgrade.workflow import WorkflowChainUpdater
from plone import api


def migrate_liveblog_workflow(context):
    """Migrate liveblog workflow."""
    review_state_mapping = {
        ('liveblog_workflow', 'simple_publication_workflow'): {
            'private': 'private',
            'active': 'published',
            'inactive': 'published',
        }
    }

    catalog = api.portal.get_tool('portal_catalog')
    query = dict(object_provides=ILiveblog.__identifier__)
    results = catalog.unrestrictedSearchResults(**query)
    objects = (b.getObject() for b in results)

    # all existing liveblogs must use now simple_publication_workflow
    wtool = api.portal.get_tool('portal_workflow')
    with WorkflowChainUpdater(objects, review_state_mapping):
        wtool.setChainForPortalTypes(
            ('Liveblog',), ('simple_publication_workflow',))
    logger.info('Liveblog objects now use simple_publication_workflow')

    # remove liveblog_workflow
    if 'liveblog_workflow' in wtool:
        api.content.delete(obj=wtool.liveblog_workflow)
        logger.info('Liveblog workflow removed')
```

my main question here is about what's being logged in my development instance where I have just one object as it seems the upgrade is running twice:

```
2016-05-25 18:06:01 INFO Zope Ready to handle requests
2016-05-25 18:06:25 INFO ftw.upgrade STARTING Get workflows and review states
2016-05-25 18:06:25 INFO ftw.upgrade 1 of 1 (100%): Get workflows and review states
2016-05-25 18:06:25 INFO ftw.upgrade DONE Get workflows and review states
2016-05-25 18:06:25 INFO ftw.upgrade STARTING Get workflows and review states
2016-05-25 18:06:25 INFO ftw.upgrade 1 of 1 (100%): Get workflows and review states
2016-05-25 18:06:25 INFO ftw.upgrade DONE Get workflows and review states
2016-05-25 18:06:25 INFO ftw.upgrade.WorkflowChainUpdater Changing workflow states of objects which were reset to the initial state according to mapping.
2016-05-25 18:06:25 INFO ftw.upgrade STARTING Change workflow states
2016-05-25 18:06:25 INFO ftw.upgrade 1 of 1 (100%): Change workflow states
2016-05-25 18:06:25 INFO ftw.upgrade DONE Change workflow states
2016-05-25 18:06:25 INFO collective.liveblog Liveblog objects now use simple_publication_workflow
2016-05-25 18:06:25 INFO collective.liveblog Liveblog workflow removed
```

any hints? what about security? do we have to do anything else?

for reference, the full code of the PR is here: https://github.com/collective/collective.liveblog/pull/31/files

CC @rodfersou

**Comment by jone** [comment]
This looks good, I think it should work exactly as intended.

The step `Get workflows and review states` is actually executed twice by intention; it just snapshots the current workflow and state of all objects, once _before_ activating the new workflow, once _after_ activating.
This is important because when activating the new workflow the current workflow state information may get lost (depending on the state names of the old and new workflows).
Having a "before" and a "after" state snapshot allows us then to update the review state according to the defined mapping.

Summarized, this happens:
- Snapshot of workflows and review states
- Activate new workflow
- Snapshots of workflows and review states
- Fix review state according to mapping and both snapshots

I would indent the logging message though, since the workflow is actually activated within the context manager. This will reorder the log so that it makes more sense:
```diff
         wtool.setChainForPortalTypes(
             ('Liveblog',), ('simple_publication_workflow',))
-    logger.info('Liveblog objects now use simple_publication_workflow')
+        logger.info('Liveblog objects now use simple_publication_workflow')
```

cheers

**Comment by hvelarde** [comment]
thanks!
