### ISSUE TITLE
Upgrade only specified profiles. [feature request]

### ISSUE THREAD

**Issue by mauritsvanrees** [4teamwork/ftw.upgrade#155]
I like to run `bin/upgrade install --site Plone --proposed` to apply all pending upgrades for all profiles. But I now have a site where this fails, because one of the installed profiles has an upgrade from `*` to `*`, which means it is always available, which leads `ftw.upgrade` to think the upgrade failed. This is a problem in that specific profile (`lineage.registry 1.3`, fixed in version 1.3.1). So I know how to fix it in this case.

But before I saw where the problem was, I tried to say on the command line: only run the pending (proposed) upgrades of one or more (other) profiles. This is not possible. You can only specify a specific upgrade step: `bin/upgrade install --site Plone --upgrades 3001@my.package:default`.

I would instead like to say this:

    bin/upgrade install --site Plone --upgrades my.package:default second.package:default

That would install all proposed upgrades for those two profiles. If no upgrades are proposed, it should finish without error.

Do you think this could be added?

**Comment by jone** [comment]
This is a good idea, thanks for the input!

Only, I'd like to still use `--proposed`, not `--upgrades`, because I could interpret that `--upgrades my.package:default` installs _all_ upgrades of this profile, even when they are already installed.
`--proposed my.package:default` on the other hand is clearer for me: it installs only the proposed upgrades of this profile.

I opened a pull request: #156
Feel free to review / comment 😉

**Comment by hvelarde** [comment]
@idgserpro this feature looks interesting also.

**Comment by jone** [comment]
This feature is implemented and released in `ftw.upgrade = 1.10.0` 🎉
