### ISSUE TITLE
product versions not updated in portal_quickinstaller / addons panel

### ISSUE THREAD

**Issue by simahawk** [4teamwork/ftw.upgrade#79]
1st of all: tnx for this addon :)

2nd: I don't know if is a plone bug or yours... but, while upgrades run smoothly, installed versions are not updated.

**Comment by jone** [comment]
Thanks :wink: and I'm happy that it seems useful :wink: 

If I understand you correctly, the Generic Setup profile version is not updated after running the upgrade steps, right?
This would mean, that after running upgrades, when navigation back to the ``manage-upgrades`` view, the just installed upgrades are still proposed and the DB-version of the profile is still "old".

This should not happen, since ftw.upgrade [sets the profile version to the destination version of the last upgrade](https://github.com/4teamwork/ftw.upgrade/blob/master/ftw/upgrade/executioner.py#L57).

Here are some thoughts:
- Only when the transaction is committed properly, the version is updated.
- When doing large upgrades, it might occur that it seems that the upgrades are finished, but the ZODB is still committing.
- When using solr (collective.solr / collective.indexing) the indexing is done after the request is finished and may take a long time with many objects and the transaction is not yet committed (we often disable solr while upgrading and then reindex it, depending on what the upgrades do).
- The browser spinner might stop spinning because of a timeout, which occurs when no more content is streamed to the response (we usually use the [ProgressLogger](https://github.com/4teamwork/ftw.upgrade#progress-logger) in upgrade steps for having "constant" output).

I don't think that it is a Plone bug, since we install upgrades directly in Generic Setup.

Which Plone version do you use? The Series 4.1, 4.2 and 4.3 are officially supported (meaning: tested).
Do you have more observations, such as warnings on the manage-upgrade view or log output which could help us?

**Comment by lukasgraf** [comment]
@jone I also missed the issue title at first - @simahawk is (only?) referring to portal_quickinstaller / the addons panel :wink:

**Comment by jone** [comment]
ah, now I got it.
I'll take a look at it. I'm not sure if the quick installer has a concept of upgrades though.

**Comment by maethu** [comment]
@jone The plone control panel of quickinstaller shows :exclamation: mark if the profile is older, than the one on the filesystem.
