### ISSUE TITLE
Support running upgrades for multiple sites

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.upgrade#81]

**Comment by jone** [comment]
The problem is that the JSON-API cannot support it because we need one request per plone site because of things such as the site-hook (`zope.component.hooks.getSite`).

We could add support in the `bin/upgrade` command though, but this can be also done quite easy be using the `sites` command, e.g.:

```shell
$ ./bin/upgrade sites --json | python -c 'import json,sys; print "\n".join([site["path"] for site in json.loads(sys.stdin.read())])' | xargs -I % bin/upgrade list -p --site %
```

I therefore think we should not add this feature to ftw.upgrade but update fix it in the scripts using `bin/upgrade`.

/cc @shylux
