### ISSUE TITLE
documentation outdated on bin/upgrade

### ISSUE THREAD

**Issue by fredvd** [4teamwork/ftw.upgrade#90]
the README.rst still mentions under installation that the bin/upgrade script has to be installed through an extra buildout recipe with zc.recipe.egg , but when I add ftw.upgrade the script is added to my bin folder without this step.

**Comment by jone** [comment]
There are recipes which recursively install all scripts.
How exactly do you add `ftw.upgrade`? 
Are you adding it as dependency to your `setup.py`? 
Or to a buildout section? (what recipe?)

**Comment by fredvd** [comment]
I'm using plone.recipe.zope2instance with zc.buildout 2.2.x  and have ftw.upgrade listed in the eggs variable.

**Comment by mauritsvanrees** [comment]
I wonder if this was a recent addition to `plone.recipe.zope2instance`. Or `zc.buildout`. There *were* some changes in recent years for this. At least it rings a bell for me.
`plone.recipe.zope2instance` says you can set a `scripts` parameter in the section of this recipe to either suppress all scripts (by making this empty) or setting it to scripts of one or more specific packages. The latest mention of this in the history is 4.2 from 2011 so that is not recent at all.

So maybe change the docs to: "The script should be installed automatically by adding `ftw.upgrade` to the eggs. If not, add it in a specific section like this:" and then the existing buildout code.

**Comment by lukasgraf** [comment]
Indeed, `plone.recipe.zope2instance` does this for as long as I can remember. I proposed some additional wording to make it clear that for this pretty common way of installing `ftw.upgrade`, no additional work is required.

**Comment by jone** [comment]
Thanks @lukasgraf for updating the documentation.
We usually do not list `ftw.upgrade` directly in the `eggs` of the `p.r.zope2instance` section, therefore we have a separate section (as far as I know the scripts are only generated for explicitly listed eggs, but not for dependencies).
