### ISSUE TITLE
Install a profile from the command line

### ISSUE THREAD

**Issue by mauritsvanrees** [4teamwork/ftw.upgrade#93]
I might replace some custom scripts by using ftw.upgrade from the command line. One thing that I then miss is the ability to install a profile. Would that be something you would consider including in your tool or would it be out of scope?
It has got nothing to do with upgrade steps, so that might make it too much. Perhaps I should do this with collective.recipe.plonesite, which supports this already. But for me it feels close to what ftw.upgrade already does.
I guess the alternative is that if I want to install new package B I can write an upgrade step for an already installed package A that does this. But that feels a bit 'meh' to me.

For reference, here is my current script, which I can of course still keep even if I replace a few others:

```
$ cat scripts/install_products.py 
# Run this with:
# bin/instance run scripts/install_products.py
from Products.CMFCore.utils import getToolByName
from zope.component.hooks import setSite
import transaction

products = [
    # 'collective.flowplayer',
    'CMFPlacefulWorkflow',
    'plone.app.dexterity',
    'clientname.jsonapi',
    ]

print('')
print('Will install these products:')
for product in products:
    print('- %s' % product)

# Get all Plone Sites.
# app is the Zope root.
plones = [obj for obj in app.objectValues()
          if getattr(obj, 'portal_type', '') == 'Plone Site']

for site in plones:
    print('')
    print('Handling Plone Site %s.' % site.id)
    setSite(site)
    qi = getToolByName(site, 'portal_quickinstaller')
    # Keep list of products that we are installing.
    installed = []
    for product in products:
        if qi.isProductInstalled(product):
            print('Already installed: %s' % product)
            continue
        if not qi.isProductInstallable(product):
            print('WARNING: not installable: %s' % product)
            continue
        print('Installing: %s' % product)
        qi.installProduct(product)
        installed.append(product)
        print('Installed: %s' % product)
    if installed:
        print('Committing transaction for Plone Site %s.' % site.id)
        # Add transaction note.
        tr = transaction.get()
        tr.note('Installed products in %s: %s' % (
            site.id, ', '.join(installed)))
        transaction.commit()
print('Done.')
```

**Comment by lukasgraf** [comment]
Without having looked into the the details of how to implement this, I'd say I could well imagine including such functionality in `ftw.upgrade`.

We'll have to see what @jone thinks once he's back.

One thing to consider though is that `ftw.upgrade` doesn't really deal with QuickInstaller products, but only GenericSetup profiles. We did include some code to avoid surprising effects where upgrade steps for products that had been uninstalled through quickinstaller were still listed (see #46 and PR #55). But that's about all that `ftw.upgrade` knows about quickinstaller, otherwise it just deals with GS profiles.

> I guess the alternative is that if I want to install new package B I can write an upgrade step for an already installed package A that does this. But that feels a bit 'meh' to me.

That's exactly what we've been doing so far. After all, if you want a reproducible setup, you'll need to introduce a dependency on that package's profile from some sort of policy profile anyway, right? And we usually then include an upgrade step in that policy that simply installs the profile for the new package. From then on, all changes beyond the initial installation are tracked as upgrade steps in the new package.

But still, I can see use cases where this would be quite handy.

**Comment by mauritsvanrees** [comment]
Ignoring QI is fine.

I can imaging installing profiles using a new command or using a new option of the current install command. If you want to install `ftw.upgrade` itself on the command line, here are some possibilities of how we might want to support this:

```
bin/upgrade install --site Plone --upgrades ftw.upgrade
bin/upgrade install --site Plone --upgrades @ftw.upgrade
bin/upgrade install --site Plone --upgrades latest@ftw.upgrade
bin/upgrade install --site Plone --new ftw.upgrade
```

The last one is of course the clearest.
The others may be fine too, but it probably makes sense to let the `--upgrade` option only do something when the profile in question is already installed.

**Comment by jone** [comment]
Although installing profiles is not primarely an upgrading issue it would be great to have this :+1: 

Since the `install` command already has an `--upgrades` argument (for upgrades) and the command would actually install the GS profile (and not run all upgrades) I would prefer using ``--profile``, e.g.:
```
bin/upgrade install --site Plone --profile my.package:default
```

**Comment by mauritsvanrees** [comment]
I would say '--profiles' in plural and allow to install multiple profiles at once, just as you can apply upgrades for multiple profiles at once.

I might work on this today.

**Comment by jone** [comment]
Cool :+1:

**Comment by jone** [comment]
Thanks @mauritsvanrees for your contributions!
I've just made a `1.16.0` release, with this change and more.

**Comment by mauritsvanrees** [comment]
Thanks for reviewing everything!
